import Card from "@/components/Globals/Card.vue";
import SvgIconVue from "@/components/Globals/SvgIcon.vue";
import Search from "@/components/Inputs/Search.vue";
import Select from "@/components/Inputs/Select.vue";
import Skeleton from "@/components/Globals/Skeleton.vue";
import Switcher from "@/components/Globals/Switcher.vue";
import Modal from "@/components/Globals/Modal.vue";
import Button from "@/components/Globals/Button.vue";
import TableLite from "vue3-table-lite";
import Loader from "@/components/Globals/Loader.vue";
import FormModal from "@/components/Globals/FormModal.vue";
import Background from "@/components/Globals/Background.vue";
import ValidInput from "@/components/Inputs/ValidInput.vue";
import ValidMultiSelect from "@/components/Inputs/ValidMultiSelect.vue";
import ValidTextarea from "@/components/Inputs/ValidTextarea.vue";
import ValidSelect from "@/components/Inputs/ValidSelect.vue";
import ValidDate from "@/components/Inputs/ValidDate.vue";
import DropFile from "@/components/Inputs/DropFile.vue";
import Image from "@/components/Inputs/Image.vue";
import Quill from "@/components/Inputs/Quill.vue";
import VOtpInput from "vue3-otp-input";
import VPagination from "@hennge/vue3-pagination";
import JsonExcel from "vue-json-excel3";
import File from "@/components/Inputs/File.vue";

export async function registerComponents(app) {
  app.component("SvgIcon", SvgIconVue);
  app.component("Card", Card);
  app.component("Search", Search);
  app.component("Select", Select);
  app.component("Skeleton", Skeleton);
  app.component("Switcher", Switcher);
  app.component("Modal", Modal);
  app.component("Button", Button);
  app.component("Table", TableLite);
  app.component("Loader", Loader);
  app.component("FormModal", FormModal);
  app.component("Background", Background);
  app.component("ValidInput", ValidInput);
  app.component("ValidTextarea", ValidTextarea);
  app.component("ValidDate", ValidDate);
  app.component("ValidSelect", ValidSelect);
  app.component("ValidMultiSelect", ValidMultiSelect);
  app.component("DropFile", DropFile);
  app.component("Image", Image);
  app.component("Quill", Quill);
  app.component("VOtpInput", VOtpInput);
  app.component("Pagination", VPagination);
  app.component("JsonExcel", JsonExcel);
  app.component("File", File);
}
